=== tests/cases/conformance/es6/arrowFunction/emitArrowFunctionWhenUsingArguments19_ES6.ts ===

function f() {
>f : () => void, Symbol(f, Decl(emitArrowFunctionWhenUsingArguments19_ES6.ts, 0, 0))

    function g() {
>g : () => void, Symbol(g, Decl(emitArrowFunctionWhenUsingArguments19_ES6.ts, 1, 14))

        var _arguments = 10;                // No capture in 'g', so no conflict.
>_arguments : number, Symbol(_arguments, Decl(emitArrowFunctionWhenUsingArguments19_ES6.ts, 3, 11))
>10 : number

        function h() {
>h : () => void, Symbol(h, Decl(emitArrowFunctionWhenUsingArguments19_ES6.ts, 3, 28))

            var capture = () => arguments;  // Should trigger an '_arguments' capture into function 'h'
>capture : () => IArguments, Symbol(capture, Decl(emitArrowFunctionWhenUsingArguments19_ES6.ts, 5, 15))
>() => arguments : () => IArguments
>arguments : IArguments, Symbol(arguments)

            foo(_arguments);                // Error as this does not resolve to the user defined '_arguments'
>foo(_arguments) : number
>foo : (x: any) => number, Symbol(foo, Decl(emitArrowFunctionWhenUsingArguments19_ES6.ts, 8, 5))
>_arguments : number, Symbol(_arguments, Decl(emitArrowFunctionWhenUsingArguments19_ES6.ts, 3, 11))
        }
    }

    function foo(x: any) {
>foo : (x: any) => number, Symbol(foo, Decl(emitArrowFunctionWhenUsingArguments19_ES6.ts, 8, 5))
>x : any, Symbol(x, Decl(emitArrowFunctionWhenUsingArguments19_ES6.ts, 10, 17))

        return 100;
>100 : number
    }
}
