() => throw new Error("Unexpected value");
